Repository LUXROBO/modi-firmware-updater, pull requests merged in 2021-06, with the labels that each got.

#7 Fix: error of window closing when exception occur
  modi_firmware_updater/core/esp32_updater.py
  modi_firmware_updater/core/stm32_updater.py
  modi_firmware_updater/gui_firmware_updater.py
Labels: size/L

#9 선택적 _thread._ExceptHookArgs 임포트 이슈 해결
  modi_firmware_updater/gui_firmware_updater.py
Labels: size/XS

#10 ESP32 Updater 인터프리터 메시지 동작 방식 수정
  modi_firmware_updater/core/esp32_updater.py
  modi_firmware_updater/gui_firmware_updater.py
Labels: size/S

#13 이슈 템플릿 번역 및 개선 진행
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/M

#17 Add black check and apply it to the code
  .flake8
  .github/workflows/build.yml
  modi_firmware_updater/core/esp32_updater.py
  modi_firmware_updater/core/gd32_updater.py
  modi_firmware_updater/core/stm32_updater.py
  modi_firmware_updater/gui_firmware_updater.py
  modi_firmware_updater/util/connection_util.py
  modi_firmware_updater/util/message_util.py
  modi_firmware_updater/util/module_util.py
  pyproject.toml
Labels: size/XL

#16 Add isort check and apply it to the code
  .github/workflows/build.yml
  modi_firmware_updater/core/esp32_updater.py
  modi_firmware_updater/core/gd32_updater.py
  modi_firmware_updater/core/stm32_updater.py
  modi_firmware_updater/gui_firmware_updater.py
  modi_firmware_updater/util/connection_util.py
  modi_firmware_updater/util/message_util.py
  modi_firmware_updater/util/module_util.py
  requirements.txt
Labels: size/L

#19 Implement an inferface for modi_firmware_updater
  modi_firmware_updater/__main__.py
Labels: size/M

#21 Implement a CLI for modi_firmware_updater
  modi_firmware_updater/__main__.py
  requirements.txt
  tests/test_gui_firmware_updater.py
Labels: size/M

#22 부트로더 상태의 모디1 네트워크 모듈 디텍션 조건 추가
  modi_firmware_updater/util/connection_util.py
Labels: size/XS
